# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
#DESTDIR = ../x64/Debug
---------------------------


QT += core gui network
greateThan(QT_MAJOR_VERSION,4): QT +=widgets
TARGET = Invoke
TEMPLATE = app

HEADERS += ./x64/Release/uic/ui_invoke.h \
    invoke.h \
    socketInvoke.h
SOURCES += invoke.cpp \
    main.cpp \ 
    socketInvoke.cpp
FORMS += invoke.ui 
INCLUDEPATH += C:/Users/pelin.kuran/vcpkg/vcpkg/installed/x64-windows/include/qt5
LIBS += -L C:/Users/pelin.kuran/vcpkg/vcpkg/installed/x64-windows/lib
RESOURCES += invoke.qrc